// <auto-generated />
using System;
using ControleFinanceiro.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiro.Database.Migrations
{
    [DbContext(typeof(ControleFinanceiroContext))]
    [Migration("20241114202014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ControleFinanceiro.Core.Entity.Entrada", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Entrada", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Data = new DateTime(2024, 11, 14, 17, 20, 14, 80, DateTimeKind.Local).AddTicks(438),
                            Nome = "Salário CAST",
                            Valor = 8000.01m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
